---
title: "KDE and BoxCox"
author: "jdt"
date: "12/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options("repos" = c(CRAN = "https://cran.rstudio.com"))
```

```{r}
if (!require("KernSmooth")) install.packages("KernSmooth", dep=TRUE)
library("KernSmooth")
bimodal <- read.table("bimodal.txt", header=TRUE)
attach(bimodal)
summary(bimodal)
```

```{r}
x <- bimodal$x
n<-length(x)
xx <- c(-300:300)/100
```

```{r}
sheather.curve = function(h,  main=" ", sub = " ") {
  truedensity = 0.5*(3/(sqrt(2*pi)))*exp(-0.5*((xx+1)/(1/3))^2)
      + 0.5*(3/(sqrt(2*pi)))*exp(-0.5*((xx-1)/(1/3))^2)
  plot( x=c(-3,3),y=c(0,0.65),type="n",xlab="x",ylab="f(x)")
  title(main=main, sub = sub)
  ysum = numeric(601)
for (i in 1:n)
  {points(x[i], 1/(n*h*sqrt(2*pi)),type="h")
     x1 = numeric(601)+x[i]
     y = (1/(h*sqrt(2*pi)))*exp(-0.5*((xx-x1)/h)^2)
     ysum = y/n + ysum
     lines(xx,y/n,lty=1)}
lines(xx,ysum,lty=1)
lines(xx,truedensity,lty=2)
}
```

```{r}
par(mfrow=c(2,2))
 sheather.curve(.2, "Sheather Bimodal Data", "with smoother = .2")
 sheather.curve(.4, " ", "with smoother = .4")
 sheather.curve(.6, " ", "with smoother = .6")
 sheather.curve(.8, " ", "with smoother = .8")
```

## The Old Faithful geyser data
Waiting Time
```{r}
par(mfrow=c(2,1))
 library(KernSmooth)
 attach(faithful)
 hist(x=waiting)
 fhat <- bkde(x=waiting)
 plot (fhat, xlab="x", ylab="Density function")
```
Eruption Time
```{r}
par(mfrow=c(2,1))
hist(x=eruptions)
 fhat <- bkde(x=eruptions)
 plot (fhat, xlab="x", ylab="Density function")
```

Regression model for Old Faithful data

```{r}
mod1 = lm(waiting ~ eruptions, data=faithful)
summary(mod1)

covb = vcov(mod1)
coeff.mod1 = coef(mod1)

covb = vcov(mod1)
covb

pred.per_fat = predict(mod1)
res.per_fat = residuals(mod1)
summary(res.per_fat)
```
Plots of regression
```{r}
par(mfrow=c(1,1))
plot(waiting,eruptions)
par(mfrow=c(1,2))
plot(mod1, which=c(1,2))
```
Box Cox transformation
```{r}
library(MASS)
boxcox(waiting ~. ,data=faithful, lambda=seq(0, 2.0, length=200))
```

ROC Curves for eruption > 3 minutes
```{r}
library(ROCR)
cut_point=(eruptions > 3)
pred = prediction(waiting,cut_point)
perf=performance(pred, "tpr", "fpr")
plot(perf)
```
 ROC Curves for eruption > 4.2 minutes
```{r}
library(ROCR)
cut_point=(eruptions > 4.2)
pred = prediction(waiting,cut_point)
perf=performance(pred, "tpr", "fpr")
plot(perf)
```
  