---
title: "R Introduction to Regression"
author: "jdt"
date: "11/26/2020"
output: latex_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Enter the Data
```{r}
x=c(15.6,26.8,37.8,36.4,35.5,18.6,15.3,7.9,0)
y=c(5.2,6.1,8.7,8.5,8.8,4.9,4.5,2.5,1.1)
```
# Non matrix approach
```{r}
n<-length(x)
ssxy<- sum((x-mean(x))*(y-mean(y)))
ssxx<- sum((x-mean(x))*(x-mean(x)))
ssyy<- sum((y-mean(y))*(y-mean(y)))
sx<-ssxx/(n-1)
sy<-ssyy/(n-1)
ssxy
sx
sy
b1<-ssxy/ssxx
b0<-mean(y)-b1*mean(x)
b0
b1
y.hat<- b0 + b1*x
y.hat
y.resid<-y - y.hat
y.resid
s.se<-sum(y.resid*y.resid)
s.se
m.se<-s.se/(n-2)
r.mse<-sqrt(m.se)
m.se
r.mse
ub1<- b1 + qt(.975,n-2)*sqrt(m.se/ssxx)
lb1<- b1 - qt(.975,n-2)*sqrt(m.se/ssxx)
ub1
lb1

u.95<-y.hat + qt(.975,n-2)*r.mse*sqrt(1/n + (x-mean(x))*(x-mean(x))/ssxx)
u.95
l.95<-y.hat - qt(.975,n-2)*r.mse*sqrt(1/n + (x-mean(x))*(x-mean(x))/ssxx)
l.95
Y<-cbind(x,y,y.hat,l.95,u.95)
Y
```
# Matrix Approach

```{r}
n<-length(x)
X<-cbind(array(1,c(n,1)),x)
B<-solve(t(X)%*%X)%*%t(X)%*%y
B
yhat<-X%*%B
yhat
resid<-y-yhat
resid
sse<-sum(resid^2)
sse
n<-dim(X)[1]
p<-dim(X)[2]
mse<-sse/(n-p)
mse
cssy<-sum((y-mean(y))^2)
rsquare<-(cssy-sse)/cssy
rsquare
stdb<-sqrt(diag(solve(t(X)%*%X))*mse)
stdb
t<-B/stdb
t
prob.1.sided<-1 - pt(t,n-p)
prob.1.sided
prob.2.sided<-1 - pf(t*t,1,n-p)
prob.2.sided

#par(mfrow=c(2,1))
plot(x,yhat,type="l")
points(x,y,col="red")
plot(x,resid)
abline(h=0)
```
# My Regression function

```{r}

my.regress<-function(x,y){
n<-length(x)
X<-cbind(array(1,c(n,1)),x)
B<-solve(t(X)%*%X)%*%t(X)%*%y
yhat<-X%*%B
resid<-y-yhat
sse<-sum(resid^2)
n<-dim(X)[1]
p<-dim(X)[2]
mse<-sse/(n-p)
rmse<-sqrt(mse)
cssy<-sum((y-mean(y))^2)
rsquare<-(cssy-sse)/cssy
covb<-(solve(t(X)%*%X))*mse
stdb<-sqrt(diag(covb))
t<-B/stdb
prob1<-1 - pt(t,n-p)
prob2<-1 - pf(t*t,1,n-p)
H<-X%*%solve(t(X)%*%X)%*%t(X)
vresid<-(diag(n)-H)*mse
vpred<-H*mse
h<-diag(H)
lowerrm95<-yhat-qt(.975,n-p)*sqrt(h*mse)
upperrm95<-yhat+qt(.975,n-p)*sqrt(h*mse)
lower95<-yhat-qt(.975,n-p)*sqrt(h*mse+mse)
upper95<-yhat+qt(.975,n-p)*sqrt(h*mse+mse)
list(x=x,y=y,Beta=B,df=n-p,yhat=yhat,resid=resid,sse=sse,
     mse=mse,rmse=rmse,rsquare=rsquare,stdb=stdb,
     covb=covb,t=t,prob1=prob1,prob2=prob2,H=H,vresid=vresid,
     vpred=vpred,h=h,lowerrm95=lowerrm95,uppperrm95=upperrm95,
     lower95=lower95,upper95=upper95)
}
```

# Plots for  My Regression
```{r}

my.regress.plot<-function(temp)
{
par(mfrow=c(2,2))
plot(temp$x,temp$yhat,type="l")
points(temp$x,temp$y,col="red")
plot(temp$x,temp$resid)
abline(h=0)
plot(temp$x,temp$h)
qqnorm(temp$resid,main="")
abline(v=0)
qqline(temp$resid)
}

result<-my.regress(x,y)
result
my.regress.plot(result)
```

#Regular R Approach to Regression
```{r}

result<-lm(y~x)
summary(result)
plot(result)
```