---
title: "Test of Fit for Two Populations"
author: "jdt"
date: "1/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options("repos" = c(CRAN = "https://cran.rstudio.com"))
```


#Analysis with Simulated Data
Using normal simulated data

```{r}
x = rnorm(75, mean=10, sd = 4)
y = rnorm(75, mean=14, sd = 4)
cert = data.frame(x,y)
#hist(x)
#hist(y)

with(cert, hist(x, main="", freq=FALSE))
with(cert, lines(density(x), main="X", lty=2, lwd=2))
xvals = with(cert, seq(from=min(x), to=max(x), length=100))
with(cert, lines(xvals, dnorm(xvals, mean(x), sd(x)), lwd=2))
with(cert, hist(y, main="", freq=FALSE))
with(cert, lines(density(y), main="", lty=2, lwd=2))
xvals = with(cert, seq(from=min(y), to=max(y), length=100))
with(cert, lines(xvals, dnorm(xvals, mean(y), sd(y)), lwd=2))
```
Descriptive statistics
```{r}
library("mosaic")
favstats(x)
mean(x, trim=.05)
quantile(x, seq(from=.025, to= .975, by=.1))
t.test(x, mu=12, conf.level=.9)   #test for mu=12 and 90 percent ci

favstats(y)
mean(y, trim=.05)
quantile(y, seq(from=.025, to= .975, by=.1))
t.test(y, mu=12, conf.level=.9)   #test for mu=12 and 90 percent ci
```

```{r}
library("coin")
wilcox.test(x,y)
t.test(x,y)
ks.test(x,y)
```

Test of fit
```{r}
library("nortest")

ad.test(x)
cvm.test(x)
lillie.test(x)
pearson.test(x)
sf.test(x)

with(cert, hist(x, main="", freq=FALSE))
with(cert, lines(density(x), main="X", lty=2, lwd=2))
xvals = with(cert, seq(from=min(x), to=max(x), length=100))
with(cert, lines(xvals, dnorm(xvals, mean(x), sd(x)), lwd=2))

qqnorm(x)
```
Repeating above with lognormal simulated data
```{r}
x = 2*rlnorm(75, mean=0, sd = 1) + 10
y = 2*rlnorm(75, mean=0, sd = 1) + 12
cert = data.frame(x,y)
#hist(x)
#hist(y)
```
Descriptive statistics
```{r}
favstats(x)
mean(x, trim=.05)
quantile(x, seq(from=.025, to= .975, by=.1))
t.test(x, mu=12, conf.level=.9)   #test for mu=12 and 90 percent ci

favstats(y)
mean(y, trim=.05)
quantile(y, seq(from=.025, to= .975, by=.1))
t.test(y, mu=12, conf.level=.9)   #test for mu=12 and 90 percent ci
```

```{r}
library("coin")
wilcox.test(x,y)
t.test(x,y)
ks.test(x,y)
```

Test of fit
```{r}

library("nortest")
ad.test(x)
cvm.test(x)
lillie.test(x)
pearson.test(x)
sf.test(x)

with(cert, hist(x, main="", freq=FALSE))
with(cert, lines(density(x), main="X", lty=2, lwd=2))
xvals = with(cert, seq(from=min(x), to=max(x), length=100))
with(cert, lines(xvals, dnorm(xvals, mean(x), sd(x)), lwd=2))

qqnorm(x)

ad.test(y)
cvm.test(y)
lillie.test(y)
pearson.test(y)
sf.test(y)

with(cert, hist(y, main="", freq=FALSE))
with(cert, lines(density(y), main="Y", lty=2, lwd=2))
xvals = with(cert, seq(from=min(y), to=max(y), length=100))
with(cert, lines(xvals, dnorm(xvals, mean(y), sd(y)), lwd=2))

qqnorm(y)
```

Repeating above with exponential simulated data
```{r}
x = rexp(75, rate = 1) 
y = rexp(75, rate = .5) 
cert = data.frame(x,y)
#hist(x)
#hist(y)
```
Descriptive statistics
```{r}
favstats(x)
mean(x, trim=.05)
quantile(x, seq(from=.025, to= .975, by=.1))
t.test(x, mu=12, conf.level=.9)   #test for mu=12 and 90 percent ci

favstats(y)
mean(y, trim=.05)
quantile(y, seq(from=.025, to= .975, by=.1))
t.test(y, mu=12, conf.level=.9)   #test for mu=12 and 90 percent ci
```

```{r}
library("coin")
wilcox.test(x,y)
t.test(x,y)
ks.test(x,y)
```

Test of fit
```{r}

library("nortest")
ad.test(x)
cvm.test(x)
lillie.test(x)
pearson.test(x)
sf.test(x)

with(cert, hist(x, main="", freq=FALSE))
with(cert, lines(density(x), main="X", lty=2, lwd=2))
xvals = with(cert, seq(from=min(x), to=max(x), length=100))
with(cert, lines(xvals, dnorm(xvals, mean(x), sd(x)), lwd=2))

qqnorm(x)

ad.test(y)
cvm.test(y)
lillie.test(y)
pearson.test(y)
sf.test(y)

with(cert, hist(y, main="", freq=FALSE))
with(cert, lines(density(y), main="Y", lty=2, lwd=2))
xvals = with(cert, seq(from=min(y), to=max(y), length=100))
with(cert, lines(xvals, dnorm(xvals, mean(y), sd(y)), lwd=2))

qqnorm(y)
```






