---
title: "Goodness of Fit Assignment"
author: Katie, Rita, and Chang
date: "8/31/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options("repos" = c(CRAN = "https://cran.rstudio.com"))
```


Analysis with Simulated normal data

```{r}
set.seed(4382)
x = rnorm(75, mean=12, sd = 7)   #x ~ N(10,4)
y = rnorm(75, mean=12, sd = 4)   #y ~ N(12,4)
cert = data.frame(x,y)
#hist(x)
#hist(y)
# When you change the mean and standard deviation of x, the Univariate Tests of Fit for Normality remain the same. 
# When you change the mean on x to 12, the p-value for the t-test becomes insignificant (this t-test has a null hypothesis that the mean is 12). The same is true when x is changed to 13. As soon as the x value goes to 11 or 14, the p-value becomes significant suggesting that there is sufficient evidence to conclude that the mean is not 12. The same is true of the t-test for the y values.
# When the mean value of x and y are the same, the p-value for the Wilcoxon rank sum test with continuity correction is not significant. However, when the mean values of x and y are at least one value apart, the p-value becomes significant (this holds as long as the standard deviations are set to 4). When the standard deviation of x is set to 10 with a mean of 11 and the standard deviation of y is set to 4 with a mean of 12, the p-value is not significant. This seems to suggests that large standard deviations make it harder to conclude that the true location shift is not equal to zero. 
# When the mean values for x and y are greater than three apart (with the same standard deviation) the p-value for the Welch Two Sample t-test becomes significant. As the values for the standard deviation are increased, the p-value for this test increases. When the mean values are further apart, but the standard deviation values are high, the p-value is not significant (ex: x mean - 16, x standard deviation - 12, y mean - 12, y standard deviation - 4).  
# The p-value for the Exact two-sample Kolmogorov-Smirnov test is significant whenever the mean values for x and y differ or the means are the same but the standard deviation values are at least three apart (ex: x mean - 12, x standard deviation - 7, y mean - 12, y standard deviation - 4).  .
with(cert, hist(x, main="", freq=FALSE))
with(cert, lines(density(x), main="X", lty=2, lwd=2))
xvals = with(cert, seq(from=min(x), to=max(x), length=100))
with(cert, lines(xvals, dnorm(xvals, mean(x), sd(x)), lwd=2))
with(cert, hist(y, main="", freq=FALSE))
with(cert, lines(density(y), main="", lty=2, lwd=2))
xvals = with(cert, seq(from=min(y), to=max(y), length=100))
with(cert, lines(xvals, dnorm(xvals, mean(y), sd(y)), lwd=2))
```

Descriptive statistics

```{r, warning=FALSE,echo=FALSE, message=FALSE}
if (!require("mosaic")) install.packages("mosaic", dep=TRUE)

library("mosaic")
favstats(x)
mean(x, trim=.05)
quantile(x, seq(from=.025, to= .975, by=.1))
t.test(x, mu=12, conf.level=.9)   #test for mu=12 and 90 percent ci

favstats(y)
mean(y, trim=.05)
quantile(y, seq(from=.025, to= .975, by=.1))
t.test(y, mu=12, conf.level=.9)   #test for mu=12 and 90 percent ci
```

Use X and Y

```{r, warning=FALSE,echo=FALSE, message=FALSE}
if (!require("coin")) install.packages("coin", dep=TRUE)

library("coin")
wilcox.test(x,y)
t.test(x,y)
ks.test(x,y)
```

Univariate Test of Fit for Normality

```{r, warning=FALSE,echo=FALSE, message=FALSE}
if (!require("nortest")) install.packages("nortest", dep=TRUE)
library("nortest")
ad.test(x)
cvm.test(x)
lillie.test(x)
pearson.test(x)
sf.test(x)


qqnorm(x)
```

Analysis with Simulated lognormal data

```{r, warning=FALSE,echo=FALSE, message=FALSE}
x = 2*rlnorm(75, mean=0, sd = 1) 
y = 2.5*rlnorm(75, mean=0, sd = 1) 

cert = data.frame(x,y)    #redefined data.frame with new x,y

with(cert, hist(x, main="", freq=FALSE))
with(cert, lines(density(x), main="X", lty=2, lwd=2))
xvals = with(cert, seq(from=min(x), to=max(x), length=100))
with(cert, lines(xvals, dnorm(xvals, mean(x), sd(x)), lwd=2))
with(cert, hist(y, main="", freq=FALSE))
with(cert, lines(density(y), main="", lty=2, lwd=2))
xvals = with(cert, seq(from=min(y), to=max(y), length=100))
with(cert, lines(xvals, dnorm(xvals, mean(y), sd(y)), lwd=2))

#use x
ad.test(x)
cvm.test(x)
lillie.test(x)
pearson.test(x)
sf.test(x)

qqnorm(x)

```

Use X and Y

```{r}
library("coin")
wilcox.test(x,y)
t.test(x,y)
ks.test(x,y)

```

Analysis with Simulated exponential data

```{r}
x = rexp(75, rate = 2) 
y = rexp(75, rate = 2.5) 

cert = data.frame(x,y)    #redefined data.frame with new x,y

with(cert, hist(x, main="", freq=FALSE))
with(cert, lines(density(x), main="X", lty=2, lwd=2))
xvals = with(cert, seq(from=min(x), to=max(x), length=100))
with(cert, lines(xvals, dnorm(xvals, mean(x), sd(x)), lwd=2))
with(cert, hist(y, main="", freq=FALSE))
with(cert, lines(density(y), main="", lty=2, lwd=2))
xvals = with(cert, seq(from=min(y), to=max(y), length=100))
with(cert, lines(xvals, dnorm(xvals, mean(y), sd(y)), lwd=2))



library("nortest")
ad.test(x)
cvm.test(x)
lillie.test(x)
pearson.test(x)
sf.test(x)


qqnorm(x)
```

Use X and Y


```{r}
library("coin")
wilcox.test(x,y)
t.test(x,y)
ks.test(x,y)


```
