---
title: "JMP_defects2"
output: html_document
date: "2023-10-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(haven)
library(tidyverse)
library(plotly)

# Read the data from the CSV file
defects <- read.csv("defects.csv")

title <- 'JMP Case Study for Defective Parts'
title2 <- 'Sampling for comparison of defects by time of day'

defects$Sample <- strptime(defects$Sample, "%H:%M")
defects$Sample <- as.POSIXct(defects$Sample)

defects <- defects %>%
  mutate(timeofday = case_when(
    between(Sample, as.POSIXct("2023-10-24 08:00:00"), as.POSIXct("2023-10-24 10:00:00")) ~ 'early',
    between(Sample, as.POSIXct("2023-10-24 10:15:00"), as.POSIXct("2023-10-24 12:00:00")) ~ 'midmorn',
    between(Sample, as.POSIXct("2023-10-24 12:15:00"), as.POSIXct("2023-10-24 14:00:00")) ~ 'midaft',
    between(Sample, as.POSIXct("2023-10-24 14:15:00"), as.POSIXct("2023-10-24 16:00:00")) ~ 'late',
    TRUE ~ NA_character_
  ))

# Summary statistics and univariate analysis
summary_stats <- summary(defects$Defects)

# Histogram and density plot
ggplot(defects, aes(x = Defects)) +
  geom_histogram(binwidth = 1, fill = "lightblue", color = "black", alpha = 0.7) +
  geom_density(alpha = 0.5, fill = "#FF6666") +
  labs(title = "Histogram and Density Plot for Defects")

# Calculate mean by timeofday
defects_summary <- defects %>%
  group_by(timeofday) %>%
  summarize(mean_defects = mean(Defects))

# Heatmap
ggplot(defects, aes(x = timeofday, y = Sample, fill = Defects)) +
  geom_tile() +
  labs(title = "Heatmap for Defects")

# ANOVA for defects
model <- glm(Day ~ timeofday, data = defects, family = gaussian)
summary(model)

```
